// <auto-generated />
namespace Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class graphs_uid_service : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(graphs_uid_service));
        
        string IMigrationMetadata.Id
        {
            get { return "202004092053500_graphs_uid_service"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
